name: Deploy MyDaily to Ubuntu Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04

    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DEPLOY_DIR: "/var/www/vitepress"
      BUILD_TAR: "dist.tar.gz"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Prepare build package
        run: |
          # 打包 dist 和图片
          mkdir -p build_package
          cp -r .vitepress/dist build_package/
          cp -r src/img build_package/dist/
          tar -czf $BUILD_TAR -C build_package .

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

      - name: Upload and deploy
        run: |
          # 上传 tar.gz 包
          scp -i ~/.ssh/id_rsa $BUILD_TAR $SSH_USER@$SSH_HOST:/tmp/$BUILD_TAR

          # 在服务器上解压并部署
          ssh -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST << EOF
            set -e
            echo "清理旧目录"
            rm -rf $DEPLOY_DIR/*
          
            echo "解压部署包"
            tar -xzf /tmp/$BUILD_TAR -C $DEPLOY_DIR --strip-components=1

            echo "重启 Nginx"
            sudo systemctl restart nginx
            sudo systemctl status nginx --no-pager

            echo "部署完成"
          EOF
